# Generated by Django 5.2.5 on 2025-08-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, unique=True, verbose_name="Name"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub Service",
                "verbose_name_plural": "Sub Services",
            },
        ),
        migrations.AddField(
            model_name="provider",
            name="sub_services",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="authentication.subservice",
                verbose_name="Sub Services",
            ),
        ),
    ]
