# Generated by Django 5.2 on 2025-06-13 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ridestatus",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="ridestatus",
            name="accepted",
        ),
        migrations.AddField(
            model_name="ridestatus",
            name="drop_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ridestatus",
            name="drop_lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ridestatus",
            name="pickup_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ridestatus",
            name="pickup_lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ridestatus",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authentication.service",
            ),
        ),
        migrations.AddField(
            model_name="ridestatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("starting", "Starting"),
                    ("arriving", "Arriving"),
                    ("finished", "Finished"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ridestatus",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rides_as_client",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ridestatus",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rides_as_provider",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
