# Generated by Django 5.2 on 2025-06-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created At"
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="is_verified",
            field=models.BooleanField(default=True, verbose_name="Is Verified"),
        ),
    ]
