# Generated by Django 5.2.5 on 2025-08-25 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_subservice_provider_sub_services"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledRide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup_lat", models.FloatField(verbose_name="Pickup Latitude")),
                ("pickup_lng", models.FloatField(verbose_name="Pickup Longitude")),
                (
                    "drop_lat",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Drop Latitude"
                    ),
                ),
                (
                    "drop_lng",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Drop Longitude"
                    ),
                ),
                ("scheduled_time", models.DateTimeField(verbose_name="Scheduled Time")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("started", "Started"),
                            ("finished", "Finished"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_as_client",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Client",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_as_provider",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Provider",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.service",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Ride",
                "verbose_name_plural": "Scheduled Rides",
                "ordering": ["-scheduled_time"],
            },
        ),
    ]
