# Generated by Django 5.2 on 2025-06-17 02:05

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import location_field.models.plain
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_rename_timestamp_ridestatus_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "Customer", "verbose_name_plural": "Customers"},
        ),
        migrations.AlterModelOptions(
            name="customerplace",
            options={
                "verbose_name": "Customer Place",
                "verbose_name_plural": "Customer Places",
            },
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "Driver", "verbose_name_plural": "Drivers"},
        ),
        migrations.AlterModelOptions(
            name="drivercar",
            options={
                "verbose_name": "Driver Car",
                "verbose_name_plural": "Driver Cars",
            },
        ),
        migrations.AlterModelOptions(
            name="provider",
            options={"verbose_name": "Provider", "verbose_name_plural": "Providers"},
        ),
        migrations.AlterModelOptions(
            name="ridestatus",
            options={
                "verbose_name": "Ride Status",
                "verbose_name_plural": "Ride Statuses",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name": "Service", "verbose_name_plural": "Services"},
        ),
        migrations.AlterModelOptions(
            name="serviceimage",
            options={
                "verbose_name": "Service Image",
                "verbose_name_plural": "Service Images",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelOptions(
            name="userotp",
            options={"verbose_name": "User OTP", "verbose_name_plural": "User OTPs"},
        ),
        migrations.AlterField(
            model_name="customer",
            name="in_ride",
            field=models.BooleanField(default=False, verbose_name="In Ride"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="customerplace",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="places",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Customer",
            ),
        ),
        migrations.AlterField(
            model_name="customerplace",
            name="location",
            field=location_field.models.plain.PlainLocationField(
                max_length=63, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="in_ride",
            field=models.BooleanField(default=False, verbose_name="In Ride"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Is Verified"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="license",
            field=models.CharField(max_length=20, unique=True, verbose_name="License"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="drivercar",
            name="color",
            field=models.CharField(max_length=20, verbose_name="Color"),
        ),
        migrations.AlterField(
            model_name="drivercar",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.driver",
                verbose_name="Driver",
            ),
        ),
        migrations.AlterField(
            model_name="drivercar",
            name="image",
            field=models.ImageField(upload_to="car/images/", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="drivercar",
            name="license",
            field=models.CharField(max_length=20, unique=True, verbose_name="License"),
        ),
        migrations.AlterField(
            model_name="drivercar",
            name="model",
            field=models.CharField(max_length=20, verbose_name="Model"),
        ),
        migrations.AlterField(
            model_name="drivercar",
            name="number",
            field=models.CharField(max_length=20, verbose_name="Number"),
        ),
        migrations.AlterField(
            model_name="drivercar",
            name="type",
            field=models.CharField(max_length=20, verbose_name="Type"),
        ),
        migrations.AlterField(
            model_name="provider",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Is Verified"),
        ),
        migrations.AlterField(
            model_name="provider",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.service",
                verbose_name="Service",
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="ridestatus",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rides_as_client",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Client",
            ),
        ),
        migrations.AlterField(
            model_name="ridestatus",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="ridestatus",
            name="drop_lat",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Drop Latitude"
            ),
        ),
        migrations.AlterField(
            model_name="ridestatus",
            name="drop_lng",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Drop Longitude"
            ),
        ),
        migrations.AlterField(
            model_name="ridestatus",
            name="pickup_lat",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Pickup Latitude"
            ),
        ),
        migrations.AlterField(
            model_name="ridestatus",
            name="pickup_lng",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Pickup Longitude"
            ),
        ),
        migrations.AlterField(
            model_name="ridestatus",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rides_as_provider",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Provider",
            ),
        ),
        migrations.AlterField(
            model_name="ridestatus",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authentication.service",
                verbose_name="Service",
            ),
        ),
        migrations.AlterField(
            model_name="ridestatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("starting", "Starting"),
                    ("arriving", "Arriving"),
                    ("finished", "Finished"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=20, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="serviceimage",
            name="image",
            field=models.ImageField(upload_to="service/images/", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="serviceimage",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="authentication.service",
                verbose_name="Service",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(upload_to="user/images/", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="user",
            name="location",
            field=location_field.models.plain.PlainLocationField(
                max_length=63, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="location2",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326, verbose_name="Location2"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=20, unique=True, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("CU", "Customer"),
                    ("DR", "Driver"),
                    ("PR", "Provider"),
                    ("AD", "Admin"),
                ],
                max_length=2,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="userotp",
            name="otp",
            field=models.CharField(max_length=20, verbose_name="OTP"),
        ),
        migrations.AlterField(
            model_name="userotp",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
