# Generated by Django 5.2 on 2025-06-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_service_created_at_alter_provider_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Is Verified"),
        ),
    ]
