# Generated by Django 5.2.5 on 2025-08-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_scheduledride"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledride",
            name="distance_km",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Distance (km)"
            ),
        ),
        migrations.AddField(
            model_name="scheduledride",
            name="duration_minutes",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Duration (minutes)"
            ),
        ),
        migrations.AddField(
            model_name="scheduledride",
            name="total_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Total Price",
            ),
        ),
    ]
