# Generated by Django 5.2 on 2025-06-21 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_provider_is_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarAgency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=50, verbose_name="Model")),
                ("brand", models.CharField(max_length=50, verbose_name="Brand")),
                ("color", models.CharField(max_length=20, verbose_name="Color")),
                (
                    "price_per_hour",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price per Hour"
                    ),
                ),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Available"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="car_agency/images/", verbose_name="Image"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("CU", "Customer"),
                    ("DR", "Driver"),
                    ("CA", "Car Agency"),
                    ("PR", "Provider"),
                    ("AD", "Admin"),
                ],
                max_length=2,
                verbose_name="Role",
            ),
        ),
        migrations.CreateModel(
            name="CarAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="Available From")),
                ("end_time", models.DateTimeField(verbose_name="Available Until")),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to="authentication.caragency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarRental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_datetime", models.DateTimeField(verbose_name="Rental Start")),
                ("end_datetime", models.DateTimeField(verbose_name="Rental End")),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Total Price",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rentals",
                        to="authentication.caragency",
                        verbose_name="Car",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_rentals",
                        to="authentication.customer",
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car Rental",
                "verbose_name_plural": "Car Rentals",
            },
        ),
    ]
