# Generated by Django 5.2 on 2025-06-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_caragency_alter_user_role_caravailability_carrental"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caragency",
            name="brand",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Brand"
            ),
        ),
        migrations.AlterField(
            model_name="caragency",
            name="color",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Color"
            ),
        ),
        migrations.AlterField(
            model_name="caragency",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="car_agency/images/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="caragency",
            name="model",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Model"
            ),
        ),
    ]
