# Generated by Django 5.2.5 on 2025-08-25 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_scheduledride_distance_km_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerservicepricing",
            name="sub_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provider_pricings",
                to="authentication.subservice",
                verbose_name="Sub Service",
            ),
        ),
    ]
