# Generated by Django 5.2.5 on 2025-08-25 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_providerservicepricing_sub_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledride",
            name="sub_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_rides",
                to="authentication.subservice",
                verbose_name="Sub Service",
            ),
        ),
    ]
