# Generated by Django 5.2 on 2025-06-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_caragency_brand_alter_caragency_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrental",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="caragency",
            name="available",
            field=models.BooleanField(default=False, verbose_name="Available"),
        ),
    ]
