# Generated by Django 5.2.5 on 2025-08-25 13:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_scheduledride_sub_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledRideRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "driver_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Driver Rating",
                    ),
                ),
                (
                    "customer_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Customer Rating",
                    ),
                ),
                (
                    "driver_comment",
                    models.TextField(blank=True, verbose_name="Driver Comment"),
                ),
                (
                    "customer_comment",
                    models.TextField(blank=True, verbose_name="Customer Comment"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "ride",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating",
                        to="authentication.scheduledride",
                        verbose_name="Scheduled Ride",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Ride Rating",
                "verbose_name_plural": "Scheduled Ride Ratings",
            },
        ),
    ]
