# Generated by Django 5.2 on 2025-06-22 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_carrental_status_alter_caragency_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="caragency",
            name="available",
        ),
    ]
