# Generated by Django 5.2 on 2025-06-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_remove_caragency_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="caragency",
            name="available",
            field=models.BooleanField(default=False, verbose_name="Available"),
        ),
    ]
