# Generated by Django 5.2.5 on 2025-08-25 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_scheduledriderating"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "restaurant_name",
                    models.CharField(max_length=200, verbose_name="Restaurant Name"),
                ),
                (
                    "restaurant_id_image",
                    models.ImageField(
                        upload_to="restaurant/logo/", verbose_name="Restaurant Logo"
                    ),
                ),
                (
                    "restaurant_license",
                    models.FileField(
                        upload_to="restaurant/license/",
                        verbose_name="Restaurant License",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Restaurant",
                "verbose_name_plural": "Restaurants",
            },
        ),
        migrations.AddField(
            model_name="provider",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.restaurantmodel",
                verbose_name="Restaurant",
            ),
        ),
    ]
