# Generated by Django 5.2.5 on 2025-09-16 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_restaurantmodel_provider_restaurant"),
    ]

    operations = [
        migrations.AddField(
            model_name="caragency",
            name="for_sale",
            field=models.BooleanField(default=False, verbose_name="For Sale"),
        ),
        migrations.AddField(
            model_name="caragency",
            name="is_sold",
            field=models.BooleanField(default=False, verbose_name="Is Sold"),
        ),
        migrations.AddField(
            model_name="caragency",
            name="sale_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Sale Price",
            ),
        ),
        migrations.CreateModel(
            name="CarPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Price"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="authentication.caragency",
                        verbose_name="Car",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_purchases",
                        to="authentication.customer",
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car Purchase",
                "verbose_name_plural": "Car Purchases",
            },
        ),
    ]
