# Generated by Django 5.2 on 2025-06-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_caragency_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="points_price",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="points_spent",
        ),
        migrations.AddField(
            model_name="product",
            name="display_price",
            field=models.PositiveIntegerField(default=0, verbose_name="Display Price"),
        ),
        migrations.AddField(
            model_name="purchase",
            name="money_spent",
            field=models.PositiveIntegerField(default=0, verbose_name="Money Spent"),
        ),
        migrations.AddField(
            model_name="purchase",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
