# Generated by Django 5.2 on 2025-06-26 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_remove_product_points_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caragency",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car_agencies",
                to="authentication.provider",
                verbose_name="Provider",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("CU", "Customer"),
                    ("DR", "Driver"),
                    ("PR", "Provider"),
                    ("AD", "Admin"),
                ],
                max_length=2,
                verbose_name="Role",
            ),
        ),
    ]
