# Generated by Django 5.2.5 on 2025-09-16 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_caragency_for_sale_caragency_is_sold_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarSaleListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Title")),
                ("brand", models.CharField(max_length=50, verbose_name="Brand")),
                ("model", models.CharField(max_length=50, verbose_name="Model")),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Year"
                    ),
                ),
                (
                    "mileage_km",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Mileage (km)"
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        blank=True,
                        choices=[("manual", "Manual"), ("automatic", "Automatic")],
                        max_length=10,
                        null=True,
                        verbose_name="Transmission",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gasoline", "Gasoline"),
                            ("diesel", "Diesel"),
                            ("hybrid", "Hybrid"),
                            ("electric", "Electric"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Fuel Type",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Color"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Price"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("is_sold", models.BooleanField(default=False, verbose_name="Is Sold")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_sale_listings",
                        to="authentication.provider",
                        verbose_name="Provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car Sale Listing",
                "verbose_name_plural": "Car Sale Listings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CarSaleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="car_sale/images/", verbose_name="Image"
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="authentication.carsalelisting",
                        verbose_name="Listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Car Sale Image",
                "verbose_name_plural": "Car Sale Images",
            },
        ),
    ]
