# Generated by Django 5.2.5 on 2025-09-16 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_carsalelisting_carsaleimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carpurchase",
            name="car",
        ),
        migrations.AddField(
            model_name="carpurchase",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="authentication.carsalelisting",
                verbose_name="Listing",
            ),
        ),
    ]
