# Generated by Django 5.2 on 2025-06-26 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_caragency_provider_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drivercar",
            name="driver",
        ),
        migrations.RemoveField(
            model_name="provider",
            name="service",
        ),
        migrations.AddField(
            model_name="provider",
            name="in_ride",
            field=models.BooleanField(default=False, verbose_name="In Ride"),
        ),
        migrations.AddField(
            model_name="provider",
            name="services",
            field=models.ManyToManyField(
                to="authentication.service", verbose_name="Services"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("CU", "Customer"), ("PR", "Provider"), ("AD", "Admin")],
                max_length=2,
                verbose_name="Role",
            ),
        ),
        migrations.CreateModel(
            name="DriverProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="License"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("available", "Available"), ("in_ride", "In Ride")],
                        default="available",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Is Verified"),
                ),
                (
                    "provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_profile",
                        to="authentication.provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver Profile",
                "verbose_name_plural": "Driver Profiles",
            },
        ),
        migrations.AddField(
            model_name="drivercar",
            name="driver_profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car",
                to="authentication.driverprofile",
            ),
        ),
        migrations.DeleteModel(
            name="Driver",
        ),
    ]
