# Generated by Django 5.2 on 2025-06-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0011_remove_drivercar_driver_remove_provider_service_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.JSONField(blank=True, default=list, verbose_name="Images"),
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
    ]
