# Generated by Django 5.2.5 on 2025-10-01 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0013_alter_productimage_options_productimage_alt_text_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantmodel",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.provider",
                verbose_name="Provider",
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_by_provider",
                to="authentication.restaurantmodel",
                verbose_name="Restaurant",
            ),
        ),
    ]
