# Generated by Django 5.2 on 2025-06-26 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0013_remove_product_images_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caravailability",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availability_slots",
                to="authentication.caragency",
                verbose_name="Car",
            ),
        ),
    ]
