# Generated by Django 5.2.5 on 2025-10-01 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0014_restaurantmodel_provider_alter_provider_restaurant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurantmodel",
            name="provider",
        ),
        migrations.AlterField(
            model_name="provider",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.restaurantmodel",
                verbose_name="Restaurant",
            ),
        ),
    ]
