# Generated by Django 5.2 on 2025-06-26 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0014_alter_caravailability_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drivercar",
            name="driver_profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car",
                to="authentication.driverprofile",
                verbose_name="Driver Profile",
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="provider",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_profile",
                to="authentication.provider",
                verbose_name="Provider",
            ),
        ),
    ]
