# Generated by Django 5.2.5 on 2025-10-01 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0015_remove_restaurantmodel_provider_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="provider",
            name="restaurant",
        ),
    ]
