# Generated by Django 5.2 on 2025-06-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0016_alter_productimage_options_alter_productimage_image_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drivercar",
            name="license",
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="documents",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="driver/documents/",
                verbose_name="Documents",
            ),
        ),
    ]
