# Generated by Django 5.2.5 on 2025-10-01 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0016_remove_provider_restaurant"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantmodel",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restaurants",
                to="authentication.provider",
                verbose_name="Provider",
            ),
        ),
    ]
