# Generated by Django 5.2.5 on 2025-10-01 11:21

import authentication.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0017_restaurantmodel_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="CouponRestaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Code"),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Discount Percentage",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Coupon",
                "verbose_name_plural": "Coupons",
            },
        ),
        migrations.AlterModelOptions(
            name="coupon",
            options={},
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
            },
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="alt_text",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="is_primary",
        ),
        migrations.AddField(
            model_name="coupon",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AddField(
            model_name="coupon",
            name="valid_from",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Valid From"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="valid_to",
            field=models.DateTimeField(
                default=authentication.models.default_coupon_valid_to,
                verbose_name="Valid To",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(max_length=20, unique=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount_percentage",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Discount Percentage"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="product_images/", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="authentication.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="sub_services",
            field=models.ManyToManyField(
                blank=True, to="authentication.subservice", verbose_name="Sub Services"
            ),
        ),
        migrations.CreateModel(
            name="ProductRestaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "display_price",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Price"
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="Stock")),
                (
                    "is_offer",
                    models.BooleanField(default=False, verbose_name="Is Offer"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products_restaurant",
                        to="authentication.productcategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Restaurant",
                "verbose_name_plural": "Product Restaurants",
                "ordering": ["name"],
                "unique_together": {("category", "name")},
            },
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.productrestaurant",
            ),
        ),
        migrations.CreateModel(
            name="ProductImageRestaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="product/images/", verbose_name="Image"
                    ),
                ),
                ("alt_text", models.CharField(max_length=255, verbose_name="Alt Text")),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Is Primary"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images_restaurant",
                        to="authentication.productrestaurant",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image Restaurant",
                "verbose_name_plural": "Product Images Restaurant",
                "ordering": ["created_at"],
                "unique_together": {("product", "image")},
            },
        ),
    ]
