# Generated by Django 5.2 on 2025-06-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0017_remove_drivercar_license_driverprofile_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="sub_service",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Sub Service"
            ),
        ),
    ]
