# Generated by Django 5.2.5 on 2025-10-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0018_couponrestaurant_alter_coupon_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productrestaurant",
            name="images",
            field=models.JSONField(default=list, blank=True),
        ),
    ]
