# Generated by Django 5.2.5 on 2025-10-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0019_productrestaurant_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productrestaurant",
            name="images",
            field=models.JSONField(blank=True, default=list, verbose_name="Images"),
        ),
    ]
