# Generated by Django 5.2.3 on 2025-06-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0019_alter_provider_sub_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="device_type",
            field=models.CharField(
                blank=True,
                choices=[("android", "Android"), ("ios", "iOS")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="fcm_registration_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="FCM Registration ID",
            ),
        ),
    ]
