# Generated by Django 5.2.5 on 2025-10-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0020_alter_productrestaurant_images"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productrestaurant",
            unique_together=set(),
        ),
    ]
