# Generated by Django 5.2.3 on 2025-06-29 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0020_user_device_type_user_fcm_registration_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("ride_request", "Ride Request"),
                            ("ride_accepted", "Ride Accepted"),
                            ("ride_status", "Ride Status Update"),
                            ("car_rental", "Car Rental Update"),
                            ("product_order", "Product Order Update"),
                            ("general", "General Notification"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Notification Type",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Additional Data"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Is Read")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
