# Generated by Django 5.2.5 on 2025-10-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0021_alter_productrestaurant_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="final_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Final Price"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Total Price"
            ),
        ),
    ]
