# Generated by Django 5.2.3 on 2025-06-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0022_customer_average_rating_provider_average_rating_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="average_rating",
        ),
        migrations.RemoveField(
            model_name="provider",
            name="average_rating",
        ),
        migrations.AddField(
            model_name="user",
            name="avarage_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=3,
                null=True,
                verbose_name="Average Rating",
            ),
        ),
    ]
