# Generated by Django 5.2.5 on 2025-10-02 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0023_alter_orderitem_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_offer",
        ),
        migrations.AddField(
            model_name="product",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="authentication.provider",
                verbose_name="Provider",
            ),
        ),
    ]
