# Generated by Django 5.2.3 on 2025-06-29 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0023_remove_customer_average_rating_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="avarage_rating",
            new_name="average_rating",
        ),
    ]
