# Generated by Django 5.2.3 on 2025-06-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0024_rename_avarage_rating_user_average_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="average_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=3,
                null=True,
                verbose_name="Average Rating",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="average_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=3,
                null=True,
                verbose_name="Average Rating",
            ),
        ),
    ]
