# Generated by Django 5.2.5 on 2025-10-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0024_remove_product_category_remove_product_is_offer_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantReportsProxy",
            fields=[],
            options={
                "verbose_name": "Restaurant Reports",
                "verbose_name_plural": "Restaurant Reports",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("authentication.restaurantmodel",),
        ),
    ]
