# Generated by Django 5.2.3 on 2025-06-29 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0025_customer_average_rating_provider_average_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="average_rating",
        ),
        migrations.RemoveField(
            model_name="provider",
            name="average_rating",
        ),
    ]
