# Generated by Django 5.2.4 on 2025-07-08 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0026_remove_customer_average_rating_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderServicePricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Application Fee",
                    ),
                ),
                (
                    "service_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Service Price",
                    ),
                ),
                (
                    "delivery_fee_per_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Delivery Fee per KM",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_pricings",
                        to="authentication.provider",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_pricings",
                        to="authentication.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider Service Pricing",
                "verbose_name_plural": "Provider Service Pricings",
                "unique_together": {("provider", "service")},
            },
        ),
    ]
