# Generated by Django 5.2.4 on 2025-07-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0027_providerservicepricing"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="providerservicepricing",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="providerservicepricing",
            name="sub_service",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Sub Service"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="providerservicepricing",
            unique_together={("provider", "service", "sub_service")},
        ),
    ]
