# Generated by Django 5.2.4 on 2025-07-23 06:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0028_alter_providerservicepricing_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Zone Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "boundaries",
                    models.JSONField(
                        help_text="Array of coordinate points defining the zone",
                        verbose_name="Zone Boundaries",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Pricing Zone",
                "verbose_name_plural": "Pricing Zones",
            },
        ),
        migrations.AddField(
            model_name="providerservicepricing",
            name="base_fare",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Fixed starting price",
                max_digits=10,
                verbose_name="Base Fare",
            ),
        ),
        migrations.AddField(
            model_name="providerservicepricing",
            name="booking_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="One-time booking fee",
                max_digits=10,
                verbose_name="Booking Fee",
            ),
        ),
        migrations.AddField(
            model_name="providerservicepricing",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created At",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="providerservicepricing",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AddField(
            model_name="providerservicepricing",
            name="minimum_fare",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Minimum total price for the ride",
                max_digits=10,
                verbose_name="Minimum Fare",
            ),
        ),
        migrations.AddField(
            model_name="providerservicepricing",
            name="peak_hour_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Multiplier for peak hours (e.g., 1.5 for 50% increase)",
                max_digits=4,
                verbose_name="Peak Hour Multiplier",
            ),
        ),
        migrations.AddField(
            model_name="providerservicepricing",
            name="peak_hours_end",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Peak Hours End"
            ),
        ),
        migrations.AddField(
            model_name="providerservicepricing",
            name="peak_hours_start",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Peak Hours Start"
            ),
        ),
        migrations.AddField(
            model_name="providerservicepricing",
            name="platform_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Fixed fee charged by the platform",
                max_digits=10,
                verbose_name="Platform Fee",
            ),
        ),
        migrations.AddField(
            model_name="providerservicepricing",
            name="price_per_km",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Price per KM"
            ),
        ),
        migrations.AddField(
            model_name="providerservicepricing",
            name="price_per_minute",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Price per Minute",
            ),
        ),
        migrations.AddField(
            model_name="providerservicepricing",
            name="service_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Additional service fee",
                max_digits=10,
                verbose_name="Service Fee",
            ),
        ),
        migrations.AddField(
            model_name="providerservicepricing",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterUniqueTogether(
            name="providerservicepricing",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="providerservicepricing",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricings",
                to="authentication.pricingzone",
                verbose_name="Pricing Zone",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="providerservicepricing",
            unique_together={("service", "sub_service", "zone")},
        ),
        migrations.RemoveField(
            model_name="providerservicepricing",
            name="application_fee",
        ),
        migrations.RemoveField(
            model_name="providerservicepricing",
            name="delivery_fee_per_km",
        ),
        migrations.RemoveField(
            model_name="providerservicepricing",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="providerservicepricing",
            name="service_price",
        ),
    ]
