# Generated by Django 5.2.4 on 2025-07-31 17:37

import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0031_alter_user_image_alter_user_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform_name",
                    models.CharField(default="Riders Admin", max_length=255),
                ),
                (
                    "platform_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="dashboard_logos/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Settings",
                "verbose_name_plural": "Platform Settings",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(upload_to="user/images/", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="user",
            name="location",
            field=location_field.models.plain.PlainLocationField(
                max_length=63, verbose_name="Location"
            ),
        ),
    ]
