# Generated by Django 5.2.4 on 2025-07-31 17:39

import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0032_platformsettings_alter_user_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="user/images/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="location",
            field=location_field.models.plain.PlainLocationField(
                blank=True, max_length=63, null=True, verbose_name="Location"
            ),
        ),
    ]
