# Generated by Django 5.2.4 on 2025-08-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0034_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="ridestatus",
            name="distance_km",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Distance (km)"
            ),
        ),
        migrations.AddField(
            model_name="ridestatus",
            name="duration_minutes",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Duration (minutes)"
            ),
        ),
        migrations.AddField(
            model_name="ridestatus",
            name="total_price",
            field=models.FloatField(blank=True, null=True, verbose_name="Total Price"),
        ),
        migrations.AddField(
            model_name="ridestatus",
            name="total_price_before_discount",
            field=models.FloatField(
                blank=True,
                help_text="Total price before applying any discounts or coupons",
                null=True,
                verbose_name="Total Price Before Discount",
            ),
        ),
    ]
