# Generated by Django 5.2.4 on 2025-08-05 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0035_ridestatus_distance_km_ridestatus_duration_minutes_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverCarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="car/images/", verbose_name="Image"),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="authentication.drivercar",
                    ),
                ),
            ],
        ),
    ]
