# Generated by Django 5.2.4 on 2025-08-05 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0036_drivercarimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drivercar",
            name="image",
        ),
    ]
