# Generated by Django 5.2.5 on 2025-08-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0038_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="onLine",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="On Line"
            ),
        ),
    ]
