# Generated by Django 5.2.5 on 2025-08-13 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0039_provider_online"),
    ]

    operations = [
        migrations.CreateModel(
            name="NameOfCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, unique=True, verbose_name="Name"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Name Of Car",
                "verbose_name_plural": "Names Of Cars",
            },
        ),
        migrations.AddField(
            model_name="provider",
            name="name_of_car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.nameofcar",
                verbose_name="Name Of Car",
            ),
        ),
    ]
