# Generated by Django 5.2.5 on 2025-08-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0040_nameofcar_provider_name_of_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverprofile",
            name="license",
            field=models.CharField(max_length=200, unique=True, verbose_name="License"),
        ),
    ]
