# Generated by Django 5.2.5 on 2025-08-13 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0041_alter_driverprofile_license"),
    ]

    operations = [
        migrations.AddField(
            model_name="ridestatus",
            name="name_of_car_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authentication.nameofcar",
                verbose_name="Name of Car",
            ),
        ),
    ]
